export type { SizeType, BaseComponentProps, InteractiveProps, SizableProps } from './common'
export type {
  SgLocale,
  TableLocale,
  PaginationLocale,
  DataGridLocale,
  ModalLocale,
  PopconfirmLocale,
  EmptyLocale,
  FormLocale,
  UploadLocale,
  TransferLocale,
  CalendarLocale,
  InputLocale,
  InputPasswordLocale,
  SearchInputLocale,
  InlineEditLocale,
  TagInputLocale,
  DrawerLocale,
  NotificationLocale,
  TagLocale,
  SpinLocale,
  SkeletonLocale,
  BreadcrumbLocale,
  CarouselLocale,
  RateLocale,
  ChartsLocale,
  DatePickerLocale,
  CascaderLocale,
  TreeSelectLocale,
  DashboardLocale,
  GanttLocale,
  ResourceCalendarLocale,
  TimelineLocale,
  SchemaFormEditorLocale,
} from './locale'
export type { SlotClassNames, SlotStyles } from './slots'
export { slotClass, slotStyle } from './slots'
